//pcscale:pc端缩放不填默认就是scale的值 为了适配pc端的不然pc端人物太小
//sznSrc填了默认src路径就是十周年UI/assets/dynamic下 为了节省空间
//配置新杀大厅骨骼
export let xinshaConfig = {
	神孙权: {
		name: "神孙权/瀚海碧君/zhujiemian_shensunquan1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 0.9,
		beijing: {
			name: "神孙权/瀚海碧君/zhujiemian_shensunquan2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威公孙瓒: {
		name: "威公孙瓒/zhujiemian_weigongsunzan1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		// pcscale: 1,
		beijing: {
			name: "威公孙瓒/zhujiemian_weigongsunzan2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威孙权: {
		name: "威孙权/zhujiemian1_weisunquan1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		// pcscale: 1,
		beijing: {
			name: "威孙权/zhujiemian1_weisunquan2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威孙尚香文: {
		name: "威孙尚香/文/zhujiemian_wensunshangxiang1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		// pcscale: 1,
		beijing: {
			name: "威孙尚香/文/zhujiemian_wensunshangxiang2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威孙尚香武: {
		name: "威孙尚香/武/zhujiemian_wusunshangxiang1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		// pcscale: 1,
		beijing: {
			name: "威孙尚香/武/zhujiemian_wusunshangxiang2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	徐妏: {
		name: "徐妏/daiji",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1.2,
		beijing: {
			name: "徐妏/beijing",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 2,
		},
	},
	威曹丕: {
		name: "威曹丕/zhujiemian_weicaopi1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		beijing: {
			name: "威曹丕/zhujiemian_weicaopi2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	谋姜维: {
		name: "谋姜维/zhujiemian1_moujiangwei1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		beijing: {
			name: "谋姜维/zhujiemian1_moujiangwei2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威马超: {
		name: "威马超/zhujiemian1_weimachao1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 0.8,
		beijing: {
			name: "威马超/zhujiemian1_weimachao2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威曹操: {
		name: "威曹操/zhujiemian_weicaocao1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		beijing: {
			name: "威曹操/zhujiemian_weicaocao2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威吕布: {
		name: "威吕布/1/yj_zhujiemian_weilvbu1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		beijing: {
			name: "威吕布/1/yj_zhujiemian_weilvbu2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	威吕布2: {
		name: "威吕布/2/zhujiemian1_weilvbu1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		// pcscale: 1,
		beijing: {
			name: "威吕布/2/zhujiemian1_weilvbu2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	神黄忠: {
		name: "神黄忠/zhujiemian_shenhuangzhong1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		// pcscale: 1.2,
		beijing: {
			name: "神黄忠/zhujiemian_shenhuangzhong2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1.1,
		},
	},
	神钟会: {
		name: "神钟会/zhujiemian_shenzhonghui1",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1,
		// pcscale: 1.2,
		beijing: {
			name: "神钟会/zhujiemian_shenzhonghui2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1,
		},
	},
	双曹·锦瑟良缘: {
		name: "曹宪曹华/锦瑟良缘/daiji",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 2,
		action: "DaiJi",
		json: "4.0",
		version: "4.0",
		beijing: {
			name: "曹宪曹华/锦瑟良缘/beijing",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 2.8,
			json: "4.0",
			version: "4.0",
		},
	},
	双曹·锦瑟良缘2: {
		name: "曹宪曹华/锦瑟良缘2/daiji",
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 2,
		json: "4.0",
		version: "4.0",
		beijing: {
			name: "曹宪曹华/锦瑟良缘2/beijing",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 2.5,
			json: "4.0",
			version: "4.0",
		},
	},
	// 模拟十周年中的皮肤文件
	// 戏志才: {
	// 	sznSrc: true,
	// 	name: "戏志才/举棋若定/XingXiang",
	// 	x: [0, 0.5],
	// 	y: [0, 0.5],
	// 	scale: 0.44,
	// 	pcscale: 1,
	// 	beijing: {
	// 		name: "戏志才/举棋若定/BeiJing",
	// 		x: [0, 0.5],
	// 		y: [0, 0.5],
	// 		scale: 2,
	// 	},
	// },
	魔貂蝉: {
		name: "魔貂蝉/幻惑欲影/daiji",
		json: true,
		x: [0, 0.5],
		y: [0, 0.5],
		scale: 1.5,
		beijing: {
			name: "魔貂蝉/幻惑欲影/beijing",
			json: true,
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 2,
		},
	},
	
};

//配置新杀斗地主页面骨骼
export let doudizhuConfig = {
	神张飞: {
		name: "神张飞/ddz_shenzhangfei1",
		x: [0, 0.5],
		y: [0, 0.5],
		pcscale: 1,
		beijing: {
			name: "神张飞/ddz_shenzhangfei2",
			x: [0, 0.5],
			y: [0, 0.5],
			scale: 1.2,
		},
	},
	谋姜维: xinshaConfig.谋姜维,
	神钟会: xinshaConfig.神钟会,
	神黄忠: xinshaConfig.神黄忠,
	魔貂蝉: xinshaConfig.魔貂蝉,
};
